paths:
    /Applications/MAMP: mamp_mac
    C:\MAMP: mamp_win

domains:
    alfahosting.de: alfahosting
    cyon.ch: cyon
    cyon.net: cyon
    goserver.host: webgo
    hosteurope.de: hosteurope
    hostpoint.ch: hostpoint
    inetrobots.com: hostingwerk
    ispgateway.de: domainfactory
    kasserver.com: allinkl
    kundenserver.de: 1und1
    netcup.net: netcup
    rzone.de: strato
    serverdomain.org: webhostone
    sui-inter.net: metanet
    tophost.ch: novatrend
    uberspace.de: uberspace
    vhost.io: hostingwerk
    your-server.de: hetzner
    etes.de: etes

networks:
    AS15817: mittwald
    AS29097: hostpoint
    AS47302: cyon

configs:
    1blu:
        name: 1blu AG
        website: www.1blu.de
        php:
            /usr/bin/php{major}{minor}/php{major}: []
            /opt/php{major}/bin/php: []

    1und1:
        name: 1&1 Internet SE
        website: www.1und1.de
        php:
            /usr/bin/php{major}.{minor}-cli: ['-d', 'memory_limit=-1']
            /usr/bin/php{major}.{minor}: []
            /usr/lib/cgi-bin/php{major}.{minor}: []

    abaton:
        name: abaton EDV-Dienstleistungs GmbH
        website: www.abaton.at
        php:
            /opt/plesk/php/{major}.{minor}/bin/php: []

    aditsystems:
        name: ADITSYSTEMS
        website: www.aditsystems.de
        php:
            /usr/bin/php{major}.{minor}: []

    alfahosting:
        name: Alfahosting GmbH
        website: alfahosting.de
        php:
            /usr/bin/php{major}.{minor}: ['-d', 'memory_limit=-1']

    allinkl:
        name: ALL-INKL.COM - Neue Medien Münnich
        website: all-inkl.com
        php:
            /usr/bin/php{major}{minor}: []
            /usr/bin/php: []

    biohost:
        name: BIOHOST
        website: www.biohost.de
        php:
            /opt/php{major}.{minor}/bin/php: []

    cyon:
        name: cyon GmbH
        website: www.cyon.ch
        php:
            /opt/alt/php{major}{minor}/usr/bin/php: []

    dogado:
        name: dogado GmbH
        website: www.dogado.de
        php:
            /opt/plesk/php/{major}.{minor}/bin/php: []

    domainfactory:
        name: domainfactory GmbH
        website: www.df.eu
        php:
            /usr/local/bin/php{major}-{major}{minor}LATEST-CLI: []

    edis:
        name: EDIS GmbH
        website: www.edis.at
        php:
            /usr/local/bin/edis-php-cli-{major}{minor}-stable-openssl: []

    etes:
        name: ETES GmbH
        website: www.etes.de
        php:
            /bin/php{major}{minor}: []

    exigo:
        name: exigo AG
        website: www.exigo.ch
        php:
            /usr/bin/php{major}.{minor}: []

    greensta:
        name: Greensta Öko Webhosting
        website: ssl.greensta.de
        php:
            /opt/phpbrew/php/php-{major}.{minor}/bin/php: []

    goneo:
        name: goneo Internet GmbH
        website: www.goneo.de
        php:
            /usr/local/phpfarm/inst/php-{major}.{minor}/bin/php: []

    hetzner:
        name: Hetzner Online GmbH
        website: www.hetzner.de
        php:
            /usr/bin/php{major}{minor}: []
            /usr/bin/php: []

    hosteurope:
        name: Host Europe GmbH
        website: www.hosteurope.de
        php:
            /usr/bin/php{major}.{minor}: ['-d', 'allow_url_fopen=1', '-d', 'memory_limit=2048M', '-d', 'suhosin.executor.include.whitelist="phar://,http://,https://"']
            /usr/bin/php: ['-d', 'allow_url_fopen=1', '-d', 'memory_limit=2048M', '-d', 'suhosin.executor.include.whitelist="phar://,http://,https://"']
            /opt/plesk/php/{major}.{minor}/bin/php: []

    hostfactory:
        name: Hostfactory (OptimaNet Schweiz AG)
        website: www.hostfactory.ch
        php:
            /opt/plesk/php/{major}.{minor}/bin/php: []

    hostnet:
        name: hostNET Medien GmbH
        website: www.hostnet.de
        php:
            /usr/iports/php{major}{minor}/bin/php: []
            /usr/local/bin/php: []

    hostpoint:
        name: Hostpoint AG
        website: www.hostpoint.ch
        php:
            /usr/local/php{major}{minor}/bin/php: []

    hostingde:
        name: hosting.de GmbH
        website: www.hosting.de
        php:
            /opt/php-{major}.{minor}/bin/php: []

    hostingwerk:
        name: Hostingwerk (Feyer Media GmbH & Co. KG)
        website: hostingwerk.de
        php:
            /usr/bin/php{major}.{minor}: []

    hosttech:
        name: Hosttech GmbH
        website: www.hosttech.eu
        php:
            /opt/plesk/php/{major}.{minor}/bin/php: []

    infomaniak:
        name: Infomaniak Network SA
        website: www.infomaniak.com
        php:
            /opt/php{major}.{minor}/bin/php: ['-d', 'allow_url_fopen=1', '-d', 'memory_limit=-1']

    iway:
        name: IWAY AG
        website: www.iway.ch
        php:
            /usr/bin/php{major}.{minor}: []

    iwelt:
        name: iWelt AG
        website: www.iwelt.de
        php:
            /opt/phpfarm/inst/php-{major}.{minor}/bin/php-cgi: []

    lahno-webhosting:
        name: Lahno Webhosting
        website: lahno-webhosting.de
        php:
            /opt/plesk/php/{major}.{minor}/bin/php: []

    mamp_mac:
        name: MAMP (macOS)
        website: www.mamp.info
        php:
            /Applications/MAMP/bin/php/php{major}.{minor}.{release}/bin/php: []

    mamp_win:
        name: MAMP (Windows)
        website: www.mamp.info
        php:
            C:\MAMP\bin\php\php{major}.{minor}.{release}\php.exe: []
            D:\MAMP\bin\php\php{major}.{minor}.{release}\php.exe: []

    manitu:
        name: manitu GmbH
        website: www.manitu.de
        php:
            /usr/local/php{major}{minor}/bin/php: []

    metanet:
        name: METANET AG
        website: www.metanet.ch
        php:
            /opt/php{major}{minor}/bin/php: []
            /usr/bin/php: []

    mittwald:
        name: Mittwald CM Service GmbH & Co. KG
        website: www.mittwald.de
        php:
            /usr/local/bin/php_cli: []

    netcup:
        name: netcup GmbH
        website: www.netcup.de
        php:
            /usr/local/php56/bin/php: ['-d', 'date.timezone=UTC']
            /usr/local/php{major}{minor}/bin/php: []
            /opt/plesk/php/{major}.{minor}/bin/php: []

    netzone:
        name: NetZone AG
        website: www.netzone.ch
        php:
            /usr/bin/php{major}.{minor}: []

    novatrend:
        name: Novatrend Services GmbH
        website: www.novatrend.ch
        php:
            /usr/local/bin/php: []

    timme:
        name: Timme Hosting GmbH & Co. KG
        website: timmehosting.de
        php:
            /opt/php-{major}.{minor}.{release}/bin/php: []

    tobiasbauer:
        name: Tobias Bauer
        website: www.tb-itf.de
        php:
            /usr/bin/php{major}{minor}: []

    serverprofis:
        name: Serverprofis GmbH
        website: www.serverprofis.de
        php:
            /opt/alt/php{major}{minor}/usr/bin/php: []

    strato:
        name: STRATO AG
        website: www.strato.de
        php:
            /opt/RZphp{major}{minor}/bin/php-cli: ['-d', 'max_execution_time=300']
            /usr/bin/php{major}.{minor}: ['-d', 'max_execution_time=300']

    uberspace:
        name: Uberspace
        website: uberspace.de
        php:
            /package/host/localhost/php-{major}.{minor}/bin/php: []
            /usr/bin/php: []

    w4w:
        name: w4w Internetservices
        website: www.w4w.net
        php:
            /usr/local/php{major}{minor}/bin/php: []

    webgo:
        name: webgo GmbH
        website: www.webgo.de
        php:
            /usr/bin/php{major}.{minor}: []
            /usr/bin/php{major}{minor}: []
            /opt/php-{major}.{minor}/bin/php: []
            /usr/bin/php: []

    webhostone:
        name: WebhostOne GmbH
        website: www.webhostone.de
        php:
            /usr/bin/php{major}{minor}: []
            /usr/bin/php: []

    wintglobal:
        name: wint.global GmbH
        website: wint.global
        php:
            /opt/plesk/php/{major}.{minor}/bin/php: []

    world4you:
        name: World4You Internet Services GmbH
        website: www.world4you.com
        php:
            /usr/bin/php{major}{minor}: []
            /usr/bin/php{major}: []

    xampp:
        name: XAMPP (Windows)
        website: www.apachefriends.org
        php:
            C:\XAMPP\php\php.exe: []
            D:\XAMPP\php\php.exe: []
