paths:
    /Applications/MAMP: mamp_mac
    C:\MAMP: mamp_win

domains:
    alfahosting.de: alfahosting
    cyon.ch: cyon
    cyon.net: cyon
    goserver.host: webgo
    hosteurope.de: hosteurope
    hostpoint.ch: hostpoint
    inetrobots.com: hostingwerk
    ispgateway.de: domainfactory
    kasserver.com: allinkl
    kundenserver.de: 1und1
    netcup.net: netcup
    rzone.de: strato
    serverdomain.org: webhostone
    sui-inter.net: metanet
    tophost.ch: novatrend
    uberspace.de: uberspace
    vhost.io: hostingwerk
    your-server.de: hetzner
    etes.de: etes

networks:
    AS15817: mittwald
    AS29097: hostpoint
    AS47302: cyon

configs:
    1und1:
        name: 1&1 Internet SE
        website: www.1und1.de
        last_update: 2017-06-20
        issues: [cputime, memory]
        php:
            /usr/bin/php{major}.{minor}-cli: ['-d', 'memory_limit=-1']
            /usr/bin/php{major}.{minor}: []
            /usr/lib/cgi-bin/php{major}.{minor}: []

    alfahosting:
        name: Alfahosting GmbH
        website: alfahosting.de
        last_update: 2017-11-17
        issues: []
        php:
            /usr/bin/php{major}.{minor}: ['-d', 'memory_limit=-1']

    allinkl:
        name: ALL-INKL.COM - Neue Medien MÃ¼nnich
        website: all-inkl.com
        last_update: 2017-06-17
        issues: []
        php:
            /usr/bin/php{major}{minor}: []
            /usr/bin/php: []

    cyon:
        name: cyon GmbH
        website: www.cyon.ch
        last_update: 2017-05-31
        issues: []
        php:
            /opt/alt/php{major}{minor}/usr/bin/php: []

    domainfactory:
        name: domainfactory GmbH
        website: www.df.eu
        last_update: 2017-06-20
        issues: [memory]
        php:
            /usr/local/bin/php{major}-{major}{minor}LATEST-CLI: []

    edis:
        name: EDIS GmbH
        website: www.edis.at
        last_update: 2017-12-01
        issues: []
        php:
            /usr/local/bin/edis-php-cli-{major}{minor}-stable-openssl: []

    etes:
        name: ETES GmbH
        website: www.etes.de
        last_update: 2017-12-15
        issues: []
        php:
            /bin/php{major}{minor}: []

    exigo:
        name: exigo AG
        website: www.exigo.ch
        last_update: 2017-12-01
        issues: []
        php:
            /usr/bin/php{major}.{minor}: []

    hetzner:
        name: Hetzner Online GmbH
        website: www.hetzner.de
        last_update: 2017-06-26
        issues: []
        php:
            /usr/bin/php{major}{minor}: []
            /usr/bin/php: []

    hosteurope:
        name: Host Europe GmbH
        website: www.hosteurope.de
        last_update: 2017-06-27
        issues: []
        php:
            /usr/bin/php{major}.{minor}: ['-d', 'allow_url_fopen=1', '-d', 'memory_limit=2048M', '-d', 'suhosin.executor.include.whitelist="phar://,http://,https://"']
            /usr/bin/php: ['-d', 'allow_url_fopen=1', '-d', 'memory_limit=2048M', '-d', 'suhosin.executor.include.whitelist="phar://,http://,https://"']

    hostfactory:
        name: Hostfactory (OptimaNet Schweiz AG)
        website: www.hostfactory.ch
        last_update: 2012-12-05
        issues: []
        php:
            /opt/plesk/php/{major}.{minor}/bin/php: []

    hostnet:
        name: hostNET Medien GmbH
        website: www.hostnet.de
        last_update: 2017-12-01
        issues: []
        php:
            /usr/iports/php{major}{minor}/bin/php: []
            /usr/local/bin/php: []

    hostpoint:
        name: Hostpoint AG
        website: www.hostpoint.ch
        last_update: 2017-12-01
        issues: []
        php:
            /usr/local/php{major}{minor}/bin/php: []

    hostingwerk:
        name: Hostingwerk (Feyer Media GmbH & Co. KG)
        website: hostingwerk.de
        last_update: 2017-06-13
        issues: []
        php:
            /usr/bin/php-{major}.{minor}: []

    mamp_mac:
        name: MAMP (macOS)
        website: www.mamp.info
        last_update: 2017-10-10
        issues: []
        php:
            /Applications/MAMP/bin/php/php{major}.{minor}.{release}/bin/php: []

    mamp_win:
        name: MAMP (Windows)
        website: www.mamp.info
        last_update: 2017-11-12
        issues: []
        php:
            C:\MAMP\bin\php\php{major}.{minor}.{release}\php.exe: []

    metanet:
        name: METANET AG
        website: www.metanet.ch
        last_update: 2017-05-31
        issues: []
        php:
            /opt/php{major}{minor}/bin/php: []
            /usr/bin/php: []

    mittwald:
        name: Mittwald CM Service GmbH & Co. KG
        website: www.mittwald.de
        last_update: 2017-11-21
        issues: []
        php:
            /usr/local/bin/php_cli: []

    netcup:
        name: netcup GmbH
        website: www.netcup.de
        last_update: 2017-06-27
        issues: []
        php:
            /usr/local/php56/bin/php: ['-d', 'date.timezone=UTC']
            /usr/local/php{major}{minor}/bin/php: []

    novatrend:
        name: Novatrend Services GmbH
        website: www.novatrend.ch
        last_update: 2017-05-31
        issues: [cputime]
        php:
            /usr/local/bin/php: []

    timme:
        name: Timme Hosting GmbH & Co. KG
        website: timmehosting.de
        last_update: 2017-12-01
        issues: []
        php:
            /opt/php-{major}.{minor}/bin/php: []

    tobiasbauer:
        name: Tobias Bauer
        website: www.tb-itf.de
        last_update: 2017-12-01
        issues: []
        php:
            /usr/bin/php{major}{minor}: []

    strato:
        name: STRATO AG
        website: www.strato.de
        last_update: 2017-05-31
        issues: [intl, memory]
        php:
            /usr/bin/php{major}.{minor}: []

    uberspace:
        name: Uberspace
        website: uberspace.de
        last_update: 2017-12-11
        issues: []
        php:
            /package/host/localhost/php-{major}.{minor}/bin/php: []
            /usr/bin/php: []

    webgo:
        name: webgo GmbH
        website: www.webgo.de
        last_update: 2017-12-21
        issues: []
        php:
            /usr/bin/php{major}{minor}: []
            /opt/php-{major}.{minor}/bin/php: []
            /usr/bin/php: []

    webhostone:
        name: WebhostOne GmbH
        website: www.webhostone.de
        last_update: 2017-06-18
        issues: []
        php:
            /usr/bin/php{major}{minor}: []
            /usr/bin/php: []
